=== jdeloren/campaigner-data/schemas/json/deity.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "D&D 5e Deities",
  "type": "array",
  "items": {
    "description": "Deity information.",
    "properties": {
      "id": {
        "description": "Unique prefixed slug ID",
        "title": "Id",
        "type": "string"
      },
      "name": {
        "description": "Deity name",
        "title": "Name",
        "type": "string"
      },
      "alignment": {
        "$ref": "common.schema.json#/$defs/Alignment",
        "description": "Alignment"
      },
      "source": {
        "description": "Source book or material",
        "title": "Source",
        "type": "string"
      },
      "pantheon": {
        "description": "Set of gods the deity belongs to",
        "title": "Pantheon",
        "type": "string"
      },
      "domains": {
        "description": "Relevant domains",
        "items": {
          "$ref": "#/$defs/Domain"
        },
        "title": "Domains",
        "type": "array"
      },
      "titles": {
        "description": "List of titles (first entry being the primary)",
        "items": {
          "type": "string"
        },
        "title": "Titles",
        "type": "array"
      },
      "power": {
        "description": "Ranking in the deity hierarchy",
        "title": "Power",
        "type": "string"
      },
      "status": {
        "description": "Theoretical state of living",
        "title": "Status",
        "type": "string"
      },
      "avatar": {
        "description": "File path for the avatar",
        "title": "Avatar",
        "type": "string"
      },
      "allies": {
        "description": "List of allies",
        "items": {
          "type": "string"
        },
        "title": "Allies",
        "type": "array"
      },
      "enemies": {
        "description": "List of enemies",
        "items": {
          "type": "string"
        },
        "title": "Enemies",
        "type": "array"
      }
    },
    "required": [
      "id",
      "name",
      "alignment",
      "source",
      "pantheon",
      "domains",
      "titles",
      "power",
      "status",
      "avatar",
      "allies",
      "enemies"
    ],
    "title": "Deity",
    "type": "object"
  },
  "$defs": {
    "Domain": {
      "enum": ["Arcana", "Death", "Knowledge", "Life", "Light", "Nature", "Order", "Tempest", "Trickery", "War"],
      "title": "Domain",
      "type": "string"
    }
  }
}

=== jdeloren/campaigner-data/data/dnd5e/deities.json
[
  {
    "id": "deity:auril",
    "name": "Auril",
    "alignment": "Neutral Evil",
    "source": "Forgotten Realms",
    "pantheon": "Faerun",
    "domains": ["Nature", "Tempest"],
    "titles": [
      "Goddess of Winter",
      "Lady Frostkiss",
      "Lady Icekiss",
      "The Cold Goddess",
      "The Queen of Cold and Frost",
      "The Frostmaiden",
      "Brittle Maiden",
      "Frost Sprite Queen",
      "Sovereign of Summers Lost",
      "General of Winter's War",
      "Winter's Womb",
      "Icedawn"
    ],
    "power": "Lesser Deity",
    "status": "Alive",
    "avatar": "Auril.jpg",
    "allies": ["Malar", "Umberlee", "Talos"],
    "enemies": ["Chauntea", "Sune", "Uthgar"]
  },
  {
    "id": "deity:azuth",
    "name": "Azuth",
    "alignment": "Lawful Neutral",
    "source": "Forgotten Realms",
    "pantheon": "Faerun",
    "domains": ["Knowledge"],
    "titles": [
      "God of Wizards",
      "Lord of Spells",
      "Lord of Spellcraft",
      "High One",
      "Patron of Wizards",
      "Hand of Sorcery",
      "The First Magister"
    ],
    "power": "God",
    "status": "Alive",
    "avatar": "Azuth.jpg",
    "allies": ["Savras", "Deneir", "Oghma", "Leira", "Mystra"],
    "enemies": []
  },
  {
    "id": "deity:bane",
    "name": "Bane",
    "alignment": "Lawful Evil",
    "source": "Forgotten Realms",
    "pantheon": "Faerun",
    "domains": ["Order", "War"],
    "titles": [
      "God of Tyranny",
      "Lord Bane",
      "Lord of Darkness",
      "The Dark One",
      "The Black Lord",
      "The Black Hand",
      "Bane the Accursed"
    ],
    "power": "Quasi-deity",
    "status": "Resurrected",
    "avatar": "Bane.jpg",
    "allies": ["Myrkul", "Loviatar", "Talona", "Mask", "Malar"],
    "enemies": ["Mystra", "Cyric", "Torm", "Oghma", "Helm"]
  },
  {
    "id": "deity:beshaba",
    "name": "Beshaba",
    "alignment": "Chaotic Evil",
    "source": "Forgotten Realms",
    "pantheon": "Faerun",
    "domains": ["Trickery"],
    "titles": [
      "Goddess of Misfortune",
      "Black Bess",
      "Lady Doom",
      "The Maid of Misfortune",
      "The Maid of Misrule",
      "The Laughing Lady of Ill Luck"
    ],
    "power": "Intermediate Deity",
    "status": "Alive",
    "avatar": "Beshaba.jpg",
    "allies": [],
    "enemies": []
  },
  {
    "id": "deity:bhaal",
    "name": "Bhaal",
    "alignment": "Neutral Evil",
    "source": "Forgotten Realms",
    "pantheon": "Faerun",
    "domains": ["Death"],
    "titles": ["God of Murder", "Lord of Murder", "Dread Lord"],
    "power": "Quasi-deity",
    "status": "Alive",
    "avatar": "Bhaal.jpg",
    "allies": ["Bane"],
    "enemies": ["Chauntea", "Helm", "Ilmater", "Lathander", "Lliira", "Tyr"]
  },
  {
    "id": "deity:chauntea",
    "name": "Chauntea",
    "alignment": "Neutral Good",
    "source": "Forgotten Realms",
    "pantheon": "Faerun",
    "domains": ["Life"],
    "titles": [
      "Goddess of Agruiculture",
      "The Great Mother",
      "The Golden Goddess",
      "Earthmother",
      "The Forest Mother",
      "She Who Shapes All",
      "Keeper of the Wild",
      "Goddess Of Bountiful Nature",
      "The Mother of All Flowers",
      "The Lady of the Harvest",
      "Grandmother"
    ],
    "power": "Greater Deity",
    "status": "Alive",
    "avatar": "Chauntea.jpg",
    "allies": ["Silvanus", "Mielikki", "Lathander"],
    "enemies": ["Talona", "Talos", "Malar", "Bane"]
  },
  {
    "id": "deity:cyric",
    "name": "Cyric",
    "alignment": "Chaotic Evil",
    "source": "Forgotten Realms",
    "pantheon": "Faerun",
    "domains": ["Trickery"],
    "titles": [
      "God of Lies",
      "Prince of Lies",
      "The Black Sun",
      "The Mad God",
      "The Lord of Three Crowns",
      "Lod of Four Crowns",
      "The Fateless",
      "The One",
      "The All",
      "The Face Behind the Mask",
      "The Everything",
      "The Most Mighty",
      "The Mad One",
      "Dark Prince",
      "Prince of Madness"
    ],
    "power": "Greater God",
    "status": "Alive",
    "avatar": "Cyric.jpg",
    "allies": [],
    "enemies": ["Mystra", "Bane", "Oghma", "Azuth", "Tyr", "Torm", "Bane", "Deneir", "Leira"]
  },
  {
    "id": "deity:deneir",
    "name": "Deneir",
    "alignment": "Neutral Good",
    "source": "Forgotten Realms",
    "pantheon": "Faerun",
    "domains": ["Knowledge"],
    "titles": ["God of Writing", "Lord of All Glyphs and Images", "The Scribe of Oghma", "The First Scribe"],
    "power": "Lesser Deity",
    "status": "Alive",
    "avatar": "Deneir.jpg",
    "allies": ["Oghma", "Gond", "Milil", "Mystra", "Azuth", "Savras"],
    "enemies": ["Cyric", "Mask", "Shar", "Malar", "Talos"]
  },
  {
    "id": "deity:eldath",
    "name": "Eldath",
    "alignment": "Neutral Good",
    "source": "Forgotten Realms",
    "pantheon": "Faerun",
    "domains": ["Life", "Nature"],
    "titles": [
      "Goddess of Peace",
      "Mother Guardian of Groves",
      "Mother of the Waters",
      "Goddess of Shining Waters",
      "Goddess of Singing Waters",
      "The Quiet One",
      "Lady of Summer"
    ],
    "power": "Lesser Deity",
    "status": "Alive",
    "avatar": "Eldath.jpg",
    "allies": ["Mielikki", "Silvanus", "Chauntea", "Selûne", "Lathander"],
    "enemies": []
  },
  {
    "id": "deity:gond",
    "name": "Gond",
    "alignment": "Neutral",
    "source": "Forgotten Realms",
    "pantheon": "Faerun",
    "domains": ["Knowledge"],
    "titles": [
      "God of Craft",
      "Holy Maker of All Things",
      "Lord of All Smiths",
      "The Gearsmith",
      "Inspiration Divine",
      "Wonderbringer"
    ],
    "power": "Intermediate Deity",
    "status": "Alive",
    "avatar": "Gond.jpg",
    "allies": ["Milil", "Deneir", "Oghma"],
    "enemies": ["Talos"]
  },
  {
    "id": "deity:helm",
    "name": "Helm",
    "alignment": "Lawful Neutral",
    "source": "Forgotten Realms",
    "pantheon": "Faerun",
    "domains": ["Life", "Light"],
    "titles": [
      "God of Protection",
      "He of the Unsleeping Eyes",
      "God of Guardians",
      "The Great Guard",
      "The Watcher",
      "The Vigilant",
      "The Vigilant One"
    ],
    "power": "Deity",
    "status": "Resurrected",
    "avatar": "Helm.jpg",
    "allies": ["Torm"],
    "enemies": ["Lathander", "Bane", "Cyric", "Mask", "Shar", "Malar", "Talos"]
  },
  {
    "id": "deity:ilmater",
    "name": "Ilmater",
    "alignment": "Lawful Good",
    "source": "Forgotten Realms",
    "pantheon": "Faerun",
    "domains": ["Life"],
    "titles": [
      "God of Endurance",
      "The Crying God",
      "The Broken God",
      "The Lord on the Rack",
      "The One Who Endures",
      "THe Rack-Broken God",
      "Our Martyred Father"
    ],
    "power": "God",
    "status": "Alive",
    "avatar": "Ilmater.jpg",
    "allies": ["Tyr", "Torm", "Lathander"],
    "enemies": ["Loviatar", "Bane", "Bhaal", "Malar", "Myrkul", "Shar", "Talos"]
  },
  {
    "id": "deity:kelemvor",
    "name": "Kelemvor",
    "alignment": "Lawful Neutral",
    "source": "Forgotten Realms",
    "pantheon": "Faerun",
    "domains": ["Death"],
    "titles": [
      "God of the Dead",
      "Lord of the Dead",
      "The Great Guide",
      "Master of the Crystal Spire",
      "Lord of the Crystal Spire",
      "Lord Death",
      "Death Lord"
    ],
    "power": "Greater Deity",
    "status": "Resurrected",
    "avatar": "Kelemvor.jpg",
    "allies": ["Lathander"],
    "enemies": ["Cyric", "Talona"]
  },
  {
    "id": "deity:lathander",
    "name": "Lathander",
    "alignment": "Neutral Good",
    "source": "Forgotten Realms",
    "pantheon": "Faerun",
    "domains": ["Life", "Light"],
    "titles": [
      "God of Birth and Renewal",
      "Morninglord",
      "Commander of Creativity",
      "Inspiration's Dawn",
      "The Rose-and-Gold God",
      "Bringer of Dawn",
      "Lord of Birth and Renewal",
      "Patron to Spring and Eternal Youth",
      "Mentor of Self-Perfection"
    ],
    "power": "Greater Deity",
    "status": "Alive",
    "avatar": "Lathander.jpg",
    "allies": ["Gond", "Tyr", "Torm", "Ilmater", "Sune", "Selûne", "Oghma", "Kelemvor", "Mielikki"],
    "enemies": ["Helm", "Cyric", "Talos", "Shar"]
  },
  {
    "id": "deity:leira",
    "name": "Leira",
    "alignment": "Chaotic Neutral",
    "source": "Forgotten Realms",
    "pantheon": "Faerun",
    "domains": ["Trickery"],
    "titles": [
      "Goddess of Illusion",
      "Lady of Deception",
      "Lady of Mists",
      "The Mistshadow",
      "Guardian of Liars",
      "Mother of Illusionists",
      "Guardian of Deception"
    ],
    "allies": ["Mask", "Azuth"],
    "enemies": ["Oghma"],
    "power": "Deity",
    "status": "Dead",
    "avatar": "deities/Leira.jpg"
  },
  {
    "id": "deity:lliira",
    "name": "Lliira",
    "alignment": "Chaotic Good",
    "source": "Forgotten Realms",
    "pantheon": "Faerun",
    "domains": ["Life"],
    "titles": ["Goddess of Joy", "Joybringer", "Our Lady of Joy", "The Everchanging Goddess", "Mistress of Revels"],
    "power": "Exarch",
    "status": "Alive",
    "avatar": "Lliira.jpg",
    "allies": ["Milil", "Deneir", "Oghma", "Waukeen"],
    "enemies": ["Shar"]
  },
  {
    "id": "deity:loviatar",
    "name": "Loviatar",
    "alignment": "Lawful Evil",
    "source": "Forgotten Realms",
    "pantheon": "Faerun",
    "domains": ["Death"],
    "titles": [
      "Goddess of Pain",
      "The Maiden of Pain",
      "The Wailing Whip",
      "The Scourge Mistress",
      "Patroness of Torturers"
    ],
    "power": "Intermediate Deity",
    "status": "Alive",
    "avatar": "Loviatar.jpg",
    "allies": ["Bane", "Bhaal", "Malar"],
    "enemies": ["Talona", "Eldath", "Lliira"]
  },
  {
    "id": "deity:malar",
    "name": "Malar",
    "alignment": "Chaotic Evil",
    "source": "Forgotten Realms",
    "pantheon": "Faerun",
    "domains": ["Nature"],
    "titles": [
      "God of the Hunt",
      "The Beastlord",
      "The Great Beast",
      "The Beast of Beasts",
      "The Bloodgod",
